spring:
  jpa:
    show-sql: false
backend:
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://d6ybckq58s9ru745.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/c9gp8l5jcf37rtra
    username: mi72r6gybgfp4ck1
    password: TpSy/M3mQEx3wnZfKe3YWFG9USnkrSXG
    connections: 4
  encryption:
    key-environment-variable-name: SLED_ENCRYPTION_KEY
  cors-origins:
    - https://marceloleite2604.github.io
    - http://marceloleite2604.github.io
    - https://isstracker.figtreelake.com
    - http://isstracker.figtreelake.com
  git:
    commit-id-abbrev: "@git.commit.id.abbrev@"
    commit-id: "@git.commit.id@"
    commit-time: "@git.commit.time@"
