spring:
  jpa:
    show-sql: true
site:
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iss_tracker_db
    username: site
    password: hjgDvAV95Yw+pJDMUvzTFi7XKZ0k3AT/
    connections: 4
  encryption:
    key: T5Sk8TKJf5G6HPvxUraKFfgcyMF2tRzf