server:
  port: 8081
inquisitor:
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iss_tracker_db
    username: inquisitor
    password: K2yXylqF/zFWHDu3p8eYqg==
    connections: 4
site:    
  encryption:
    key: 5n9rT9ZKqAF6tk8OJqRU+FRGjBrmiVd8