spring:
  profiles:
    active:
    - "@activeProfile@"
inquisitor:
  # locale: pt-br
  # zone-id: America/Sao_Paulo
  api-base-url: http://api.open-notify.org
  route-map:
    generation:
      update-time-minutes: 10
      minimal-positions: 10
    style:
      route-color: "0xff000050"
      marker-color: "0xff0000a0"
      image-size: 640x480
  encryption:
    cryptographic-algorythm: DESede
    feedback-mode: CBC
    padding-scheme: PKCS5Padding
  google:
    api-key-environment-variable: GOOGLE_API_KEY
    maps-static-api-url: https://maps.googleapis.com/maps/api/staticmap