server:
  port: 8080
  servlet:
    context-path: /iss-tracker
spring:
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/thymeleaf/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    template-resolver-order: 0
    cache: false
site:
  # locale: pt-br
  # zone-id: America/Sao_Paulo
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iss_tracker_db
    username: site
    password: hjgDvAV95Yw+pJDMUvzTFi7XKZ0k3AT/
    connections: 4
  encryption:
    cryptographic-algorythm: DESede
    feedback-mode: CBC
    padding-scheme: PKCS5Padding
    key: T5Sk8TKJf5G6HPvxUraKFfgcyMF2tRzf
