server:
  port: ${PORT:8080}
spring:
  profiles:
    active:
    - "@activeProfile@"
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/thymeleaf/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    template-resolver-order: 0
    cache: false
site:
  # locale: pt-br
  # zone-id: America/Sao_Paulo
  encryption:
    cryptographic-algorythm: DESede
    feedback-mode: CBC
    padding-scheme: PKCS5Padding
